### PR TITLE
fix: [CI-12038]: Add LFS support for windows

### PR DESCRIPTION
**Pull request by jamie-harness**

### CODE REVIEW

**Comment by hemanthmantri** [comment]
All amd64 and no arm64?

**Comment by jamie-harness** [comment]
> All amd64 and no arm64?

@hemanthmantri yes. All our windows images are AMD. I don't think there's an ARM k8s support by anyone yet

**Review by hemanthmantri — APPROVED** [review]

**Review by raghavharness — APPROVED** [review]
Have we tried to build it ? If yes can we attach the build links here. Also how much increase in docker image size is expected here ?

**Review by vistaarjuneja — APPROVED** [review]
Approved as long as we've tested that images are generated correctly.
+1 to @raghavharness's query on docker image size increase, I'm guessing it should not be much increase.

**Comment by jamie-harness** [comment]
I built locally. The image size is about 3mb bigger than before after compress

**Review by devkimittal — APPROVED** [review]

**Pull request merged**
